#pragma once
// GDAL-only NetCDF file wrapper. Does not expose any netCDF C++ types in the public API.

#include "nctools.h"
#include <macgyver/DateTime.h>
#include <macgyver/StringConversion.h>
#include <newbase/NFmiTimeList.h>
#include <gdal.h>
#include <memory>
#include <optional>
#include <string>
#include <vector>

class NFmiFastQueryInfo;

namespace nctools
{

class NcFileExtended
{
 public:
  std::string path;
  long timeshift = 0;

  NcFileExtended(std::string path, long timeshift = 0);
  ~NcFileExtended();

  bool is_open() const { return gdal_dataset != nullptr; }

  void setOptions(const Options& opts) { options = opts; }
  void setWRF(bool mode) { wrf = mode; }

  void initAxis(const std::optional<std::string>& xname,
                const std::optional<std::string>& yname,
                const std::optional<std::string>& zname,
                const std::optional<std::string>& tname);

  void printInfo() const;

  bool has_x_axis() const { return !x_name.empty(); }
  bool has_y_axis() const { return !y_name.empty(); }
  bool has_z_axis() const { return !z_name.empty(); }
  bool has_t_axis() const { return !t_name.empty(); }

  std::string x_units() const;
  std::string y_units() const;
  std::string z_units() const;

  bool is_dim(const std::string& name) const;
  bool axis_match(const std::string& varname) const;

  std::string grid_mapping();
  unsigned long xsize() const { return _xsize; }
  unsigned long ysize() const { return _ysize; }
  unsigned long zsize() const { return _zsize; }
  unsigned long tsize() const { return _tsize; }

  float get_missingvalue_for_var(const std::string& varname) const;
  std::string get_standard_name(const std::string& varname) const;
  std::vector<long> get_z_values() const;

  double x_scale();
  double y_scale();
  double z_scale();

  double xmin();
  double xmax();
  double ymin();
  double ymax();
  double zmin();
  double zmax();

  bool xinverted();
  bool yinverted();
  bool isStereographic();

  double longitudeOfProjectionOrigin = 0;
  double latitudeOfProjectionOrigin = 0;

  void copy_values(const Options& options,
                   NFmiFastQueryInfo& info,
                   const ParamConversions& paramconvs,
                   bool useAutoGeneratedIds);

  bool joinable(NcFileExtended& ncfile, std::vector<std::string>* failreasons = nullptr);

  NFmiTimeList timeList(std::string varName = "time", std::string unitAttrName = "units");

  // Returns variable names in the order they appear in the file (GDAL subdataset order).
  // Only returns data variables, not coordinate variables (lat, lon, time, lev, etc.).
  std::vector<std::string> get_gdal_variable_names() const;

  void require_conventions(const std::string* reference);

 private:
  GDALDatasetH gdal_dataset = nullptr;

  std::string x_name, y_name, z_name, t_name;

  // Cached axis sizes (set in initAxis; _xsize/_ysize also set in load_first_var_meta)
  mutable unsigned long _xsize = 0;
  mutable unsigned long _ysize = 0;
  unsigned long _zsize = 1;
  unsigned long _tsize = 0;

  // Cached axis scale values
  double xscale_ = 0;
  double yscale_ = 0;
  double zscale_ = 0;
  bool x_scale_set_ = false;
  bool y_scale_set_ = false;
  bool z_scale_set_ = false;

  bool minmaxfound = false;
  double _xmin = 0, _xmax = 0;
  double _ymin = 0, _ymax = 0;
  double _zmin = 0, _zmax = 0;
  bool _xinverted = false;
  bool _yinverted = false;
  bool _y_lat_irregular = false;  // true when y-axis lat is irregular (GDAL resamples to ascending)

  std::shared_ptr<std::string> projectionName;
  bool wrf = false;
  Options options;

  std::shared_ptr<NFmiTimeList> timelist;

  // Cached first-variable metadata (key=value pairs from GDAL metadata, "key#attr" format)
  // mutable to allow lazy initialization in const methods
  mutable std::map<std::string, std::string> first_var_meta_;
  mutable std::string first_var_name_;

  // GDAL helpers
  std::string open_var_ds_name(const std::string& varname) const;
  GDALDatasetH open_var_dataset(const std::string& varname) const;
  std::string get_first_var_meta(const std::string& key) const;
  std::string get_coord_attr(const std::string& coordname, const std::string& attrname) const;
  std::vector<double> get_dim_values_double(const std::string& dimname) const;
  unsigned long compute_dim_size(const std::string& dimname) const;
  std::string get_subdataset_desc(const std::string& varname) const;
  std::vector<long> parse_desc_dims(const std::string& desc) const;
  double axis_scale_from_units(const std::string& units) const;

  void load_first_var_meta() const;
  void merge_dim_meta(const std::string& dimname) const;  // merge metadata from a var that has dimname
  void find_bounds();
  void find_axis_bounds_gdal(const std::string& coordname,
                             unsigned long n,
                             double& x1,
                             double& x2,
                             const char* label,
                             bool& isdescending,
                             bool* is_irregular = nullptr);
  void find_lonlat_bounds(double& lon1, double& lat1, double& lon2, double& lat2);

  void copy_values_var(const Options& opts,
                       const std::string& varname,
                       NFmiFastQueryInfo& info);
  void copy_values_wind(NFmiFastQueryInfo& info,
                        const ParamInfo& pinfo,
                        const Options* opts);
};

// Free functions
NFmiMetTime tomettime(const Fmi::DateTime& t);
unsigned long get_units_in_seconds(std::string unit_str);
void parse_time_units_string(const std::string& units_str,
                             Fmi::DateTime* origintime,
                             long* timeunit);

}  // namespace nctools
