.TH QDCOMBINE 1 "2026-05-02" "smartmet-qdtools" "SmartMet Tools"
.SH NAME
qdcombine \- combine multiple querydata files into one
.SH SYNOPSIS
.B qdcombine
.RI [ options ]
.I directory
.RI [ "file2 file3" ...] >
.I output
.br
.B qdcombine
.RI [ options ]
.B \-o
.RI [ outfile ]
.I directory
.RI [ "file2 file3" ...]
.br
.B qdcombine
.RI [ options ]
.B \-O
.RI [ mmapped_outfile ]
.I directory
.RI [ "file2 file3" ...]
.SH DESCRIPTION
.B qdcombine
merges all querydata files from the given directory (or files) into a
single output. Times, parameters and levels are unioned. The inputs
must share the same projection and grid size unless point data is being
combined.
.SH OPTIONS
.TP
.BI \-o " outfile"
Output filename (default is standard output).
.TP
.BI \-O " outfile"
Memory-mapped output filename.
.TP
.B \-P
Combine point data instead of grid data.
.TP
.BI \-l " levelType[,value]"
Set the level type and value (e.g.\&
.I 5000,0
for normal ground data).
.TP
.BI \-p " id,name"
Set the producer id and name (e.g.\&
.IR 240,ecmwf ).
.SH EXAMPLES
Combine all files in a directory:
.PP
.RS 4
qdcombine /data/forecast > combined.sqd
.RE
.PP
Memory-mapped output and a custom producer:
.PP
.RS 4
qdcombine \-p 240,ecmwf \-O combined.sqd /data/forecast
.RE
.SH SEE ALSO
.BR combineHistory (1),
.BR qdcrop (1),
.BR qdsplit (1),
.BR qdinfo (1)
.SH AUTHOR
Finnish Meteorological Institute
.PP
Report issues at <https://github.com/fmidev/smartmet-qdtools/issues>.
